server:
  port: 9009

spring:
  application:
    name: tensquare-sms
  rabbitmq:
    host: 192.168.2.130

aliyun:
  sms:
    accessKeyId: ****
    accessKeySecret: ***
    template_code: ***
    sign_name: ***



