server:
  port: 9001
spring:
  application:
    name: tensquare‐base #指定服务名
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.130:3306/tensquare_base
    username: root
    password: mima
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:6868/eureka/
  instance:
    prefer-ip-address: true