server:
  port: 9010
spring:
  application:
    name: tensquare-friend
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.130:3306/tensquare_friend?characterEncoding=utf-8
    username: root
    password: mima
  jpa:
    database: MySQL
    show‐sql: true
    generate‐ddl: true

jwt:
  config:
    key: paulson

eureka:
  client:
    service-url:
      defaultZone: http://192.168.2.130:6868/eureka/
  instance:
    prefer-ip-address: true
