server:
  port: 12000
spring:
  application:
    name: tensquare-config
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/paulsonwier/tensquare_dev.git

  rabbitmq:
    host: 192.168.2.130

management:
  endpoints:
    web:
      exposure:
        include: bus-refresh