server: 
  port: 9005
spring: 
  application:  
    name: tensquare-gathering #指定服务名
  datasource:  
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.2.130:3306/tensquare_gathering
    username: root
    password: mima
  jpa: 
    database: MySQL
    show-sql: true
